#
# Copyright (c) 2020 FTI-CAS
#

VM_STATUS_SHUTOFF = 'SHUTOFF'
VM_STATUS_ACTIVE = 'ACTIVE'
VM_STATUS_BUILD = 'BUILD'
VM_STATUS_REBUILD = 'REBUILD'
VM_STATUS_RESIZE = 'RESIZE'
VM_STATUS_VERIFY_RESIZE = 'VERIFY_RESIZE'
VM_STATUS_MIGRATING = 'MIGRATING'
VM_STATUS_ERROR = 'ERROR'
VM_STATUS_DELETED = 'DELETED'
VM_STATUS_UNKNOWN = 'UNKNOWN'

VM_POWER_STATE = [
    (1, 'NOSTATE'),
    (2, 'RUNNING'),
    (3, 'PAUSED'),
    (4, 'SHUTDOWN'),
    (5, 'CRASHED'),
    (6, 'SUSPENDED'),
]

DEFAULT_NET_MTU_SIZE = 1500

IS_EXISTING = 'is_existing'
IS_PUBLIC = 'is_public'
